name: AI Summarizer
on: [push]
jobs:
  run-python-script:
    name: Summarize Changes
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with your required Python version

      # Install dependencies (optional)
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt # Ensure your repo has a requirements.txt file