name: AI Summarizer
on: [push]
jobs:
  run-python-script:
    name: Summarize Changes
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@main

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.x" # Replace with your required Python version
      - name: Load OpenAI Tokens from 1Password
        id: op-ai-creds
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OPEN_AI_PROJECT: op://ci-cd/OpenAI CI-CD Credential/username
          OPEN_AI_KEY: op://ci-cd/OpenAI CI-CD Credential/credential
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
      - name: Print masked secret
        run: 'echo "OPEN_AI_PROJECT: ${{ steps.op-ai-creds.outputs.OPEN_AI_PROJECT }} \nOPEN_AI_KEY:${{ steps.op-ai-creds.outputs.OPEN_AI_KEY }}"'
      - name: Run Append Dad Joke Script
        run: |
          python append_dad_joke.py
        env:
          OPENAI_API_KEY: ${{ steps.op-ai-creds.outputs.OPEN_AI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
